version: '3.0'

scanning-settings:
  max-depth: 6
  exclude:
    - "node_modules"
    - ".venv"
    - "**/*.js"

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: false
        unpinned-requirements: false
      cvss-severity: []
      vulnerabilities: {}

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
        - high

ignore:
  dependency-vulnerabilities:
    python:
      # Add any CVEs to ignore here (previously in security.ignore-vulnerabilities)
      vulnerabilities:
        - id: "12345"
          reason: "Example CVE to ignore"

      # Add any packages to ignore here (previously in security.ignore-packages)
      packages:
        - name: "package-name"
          reason: "Example package to ignore"
