version: '3.0'

scanning-settings:
  max-depth: 6
  exclude:
    - "node_modules"
    - ".venv"
    - "**/*.js"

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: false
        unpinned-requirements: false
      cvss-severity: []
      vulnerabilities: {}

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
        - high
