version: "3.8"

services:
  llm-rag-api:
    image: llm-rag:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./chroma_db:/app/chroma_db
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
