apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-rag
  labels:
    app: llm-rag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm-rag
  template:
    metadata:
      labels:
        app: llm-rag
    spec:
      containers:
      - name: llm-rag
        image: ${DOCKERHUB_USERNAME}/llm-rag:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: CLOUD_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: cloud-provider-config
              key: CLOUD_PROVIDER
