apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-rag
  labels:
    app: llm-rag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm-rag
  template:
    metadata:
      labels:
        app: llm-rag
    spec:
      initContainers:
      - name: detect-cloud-provider
        image: busybox:stable
        command:
          - "/bin/sh"
          - "-c"
          - |
            if curl -s -f http://metadata.google.internal; then
              echo "CLOUD_PROVIDER=GCP" > /configmap-volume/CLOUD_PROVIDER
            elif curl -s -f http://169.254.169.254/latest/meta-data; then
              echo "CLOUD_PROVIDER=AWS" > /configmap-volume/CLOUD_PROVIDER
            else
              echo "CLOUD_PROVIDER=UNKNOWN" > /configmap-volume/CLOUD_PROVIDER
            fi
        volumeMounts:
        - name: configmap-volume
          mountPath: /configmap-volume

      containers:
      - name: llm-rag
        image: ${DOCKERHUB_USERNAME}/llm-rag:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: CLOUD_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: cloud-provider-config
              key: CLOUD_PROVIDER
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: cloud-provider-config
              key: ENVIRONMENT

      volumes:
      - name: configmap-volume
        configMap:
          name: cloud-provider-config
