apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  labels:
    app: llm-rag
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # No storageClassName for local testing with KIND
  storageClassName: ""
