apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: llm-rag-network-policy
  labels:
    app: llm-rag
spec:
  podSelector:
    matchLabels:
      app: llm-rag
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
