apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  labels:
    app: llm-rag
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
