apiVersion: v1
kind: Service
metadata:
  name: llm-rag-service
  labels:
    app: llm-rag
spec:
  selector:
    app: llm-rag
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: LoadBalancer  # Use ClusterIP if internal-only
