apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base directory
resources:
- ../../
- ingress.yaml
- pdb.yaml

# Add production-specific labels
commonLabels:
  environment: production

# Generate ConfigMap with environment-specific values
configMapGenerator:
- name: llm-rag-env
  behavior: merge
  literals:
  - APP_ENV=production
  - LOG_LEVEL=INFO
  - DEBUG_MODE=false
  - MAX_CONCURRENT_REQUESTS=30
  - QUERY_TIMEOUT_SECONDS=60

# Patch resources with production-specific configurations
patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml
- service-patch.yaml

# Set namespace for all resources
namespace: llm-rag-prod

# Production replica settings
replicas:
- name: llm-rag
  count: 3
