apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: llm-rag-pdb
  labels:
    app: llm-rag
spec:
  minAvailable: 2  # At least 2 pods must be available during disruptions
  selector:
    matchLabels:
      app: llm-rag
