name: Container Security Scan

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

on:
  pull_request:
    branches: [main]
    paths:
      - "Dockerfile"
      - ".github/trivy-container.yml"
  workflow_dispatch:
  schedule:
    # Run weekly on Monday at 1:00 AM UTC
    - cron: "0 1 * * 1"

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: localhost/llm-rag:${{ github.sha }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check image
        run: docker image ls | grep localhost/llm-rag

      # Cache Trivy DB to speed up subsequent scans
      - name: Cache Trivy vulnerability database
        uses: actions/cache@v4
        with:
          path: .trivy-cache
          key: trivy-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            trivy-${{ runner.os }}-

      # Basic scan for vulnerabilities
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localhost/llm-rag:${{ github.sha }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          timeout: "10m"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"

      # Comprehensive scan including secrets and config
      - name: Run comprehensive Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localhost/llm-rag:${{ github.sha }}
          format: "sarif"
          output: "trivy-comprehensive.sarif"
          severity: "CRITICAL,HIGH,MEDIUM"
          timeout: "10m"
          exit-code: "0" # Don't fail on medium issues
          ignore-unfixed: true
          scan-type: "vuln,secret,config"

      - name: Upload vulnerability scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
          category: "trivy-container"

      - name: Upload comprehensive scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-comprehensive.sarif"
          category: "trivy-container-comprehensive"

      # Generate report for PR comment
      - name: Generate scan summary for PR comment
        if: github.event_name == 'pull_request'
        run: |
          # Install trivy CLI for text report
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

          # Generate table format report
          trivy image --format table localhost/llm-rag:${{ github.sha }} > trivy-summary.txt

          # Create markdown summary
          {
            echo "## 🔒 Container Security Scan Results"
            echo "### Image: \`localhost/llm-rag:${{ github.sha }}\`"
            echo ""
            echo "<details><summary>View detailed scan results</summary>"
            echo ""
            echo '```'
            cat trivy-summary.txt
            echo '```'
            echo ""
            echo "</details>"
          } > trivy-summary.md

      - name: Comment PR with scan results
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-summary.md
          header: container-scan
